ein: std::numeric_limits< ein::bf16 > Class Reference
std::numeric_limits< ein::bf16 > Class Reference
#include <bf16.hpp>
Static Public Member Functions
static constexpr ein::bf16 min () noexcept
static constexpr ein::bf16 max () noexcept
static constexpr ein::bf16 lowest () noexcept
static constexpr ein::bf16 epsilon () noexcept
static constexpr ein::bf16 round_error () noexcept
static constexpr ein::bf16 infinity () noexcept
static constexpr ein::bf16 quiet_NaN () noexcept
static constexpr ein::bf16 signaling_NaN () noexcept
static constexpr ein::bf16 denorm_min () noexcept
Static Public Attributes
static constexpr bool is_specialized = true
static constexpr int digits = 7
static constexpr int digits10 = 2
static constexpr bool is_signed = true
static constexpr bool is_integer = false
static constexpr bool is_exact = false
static constexpr int radix = 2
static constexpr int min_exponent = -125
static constexpr int min_exponent10 = -37
static constexpr int max_exponent = 128
static constexpr int max_exponent10 = 38
static constexpr bool has_infinity = true
static constexpr bool has_quiet_NaN = true
static constexpr bool has_signaling_NaN = true
static constexpr float_denorm_style has_denorm = denorm_absent
static constexpr bool has_denorm_loss = false
static constexpr bool is_iec559 = false
static constexpr bool is_bounded = false
static constexpr bool is_modulo = false
static constexpr bool traps = false
static constexpr bool tinyness_before = false
static constexpr float_round_style round_style = round_to_nearest
Detailed Description
Definition at line 136 of file bf16.hpp.
Member Function Documentation
denorm_min()
static constexpr ein::bf16 std::numeric_limits< ein::bf16 >::denorm_min () inline static constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 187 of file bf16.hpp.
{
      return ein::bf16{};
    }
epsilon()
static constexpr ein::bf16 std::numeric_limits< ein::bf16 >::epsilon () inline static constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 158 of file bf16.hpp.
{
      return ein::bf16::from_bits(0x3C00);
    }
References ein::bf16::from_bits().
infinity()
static constexpr ein::bf16 std::numeric_limits< ein::bf16 >::infinity () inline static constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 175 of file bf16.hpp.
{
      return ein::bf16::from_bits(0x7F80);
    }
References ein::bf16::from_bits().
lowest()
static constexpr ein::bf16 std::numeric_limits< ein::bf16 >::lowest () inline static constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 148 of file bf16.hpp.
{
      return ein::bf16::from_bits(0xFF7F);
    }
References ein::bf16::from_bits().
max()
static constexpr ein::bf16 std::numeric_limits< ein::bf16 >::max () inline static constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 144 of file bf16.hpp.
{
      return ein::bf16::from_bits(0x7F7F);
    }
References ein::bf16::from_bits().
min()
static constexpr ein::bf16 std::numeric_limits< ein::bf16 >::min () inline static constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 140 of file bf16.hpp.
{
      return ein::bf16::from_bits(0x007F);
    }
References ein::bf16::from_bits().
quiet_NaN()
static constexpr ein::bf16 std::numeric_limits< ein::bf16 >::quiet_NaN () inline static constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 179 of file bf16.hpp.
{
      return ein::bf16::from_bits(0x7FC0);
    }
References ein::bf16::from_bits().
round_error()
static constexpr ein::bf16 std::numeric_limits< ein::bf16 >::round_error () inline static constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 162 of file bf16.hpp.
{
      return ein::bf16::from_bits(0x3F00);
    }
References ein::bf16::from_bits().
signaling_NaN()
static constexpr ein::bf16 std::numeric_limits< ein::bf16 >::signaling_NaN () inline static constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 183 of file bf16.hpp.
{
      return ein::bf16::from_bits(0x7FC0);
    }
References ein::bf16::from_bits().
Member Data Documentation
digits
int std::numeric_limits< ein::bf16 >::digits = 7 static constexpr
Definition at line 151 of file bf16.hpp.
digits10
int std::numeric_limits< ein::bf16 >::digits10 = 2 static constexpr
Definition at line 152 of file bf16.hpp.
has_denorm
float_denorm_style std::numeric_limits< ein::bf16 >::has_denorm = denorm_absent static constexpr
Definition at line 172 of file bf16.hpp.
has_denorm_loss
bool std::numeric_limits< ein::bf16 >::has_denorm_loss = false static constexpr
Definition at line 173 of file bf16.hpp.
has_infinity
bool std::numeric_limits< ein::bf16 >::has_infinity = true static constexpr
Definition at line 169 of file bf16.hpp.
has_quiet_NaN
bool std::numeric_limits< ein::bf16 >::has_quiet_NaN = true static constexpr
Definition at line 170 of file bf16.hpp.
has_signaling_NaN
bool std::numeric_limits< ein::bf16 >::has_signaling_NaN = true static constexpr
Definition at line 171 of file bf16.hpp.
is_bounded
bool std::numeric_limits< ein::bf16 >::is_bounded = false static constexpr
Definition at line 191 of file bf16.hpp.
is_exact
bool std::numeric_limits< ein::bf16 >::is_exact = false static constexpr
Definition at line 155 of file bf16.hpp.
is_iec559
bool std::numeric_limits< ein::bf16 >::is_iec559 = false static constexpr
Definition at line 190 of file bf16.hpp.
is_integer
bool std::numeric_limits< ein::bf16 >::is_integer = false static constexpr
Definition at line 154 of file bf16.hpp.
is_modulo
bool std::numeric_limits< ein::bf16 >::is_modulo = false static constexpr
Definition at line 192 of file bf16.hpp.
is_signed
bool std::numeric_limits< ein::bf16 >::is_signed = true static constexpr
Definition at line 153 of file bf16.hpp.
is_specialized
bool std::numeric_limits< ein::bf16 >::is_specialized = true static constexpr
Definition at line 138 of file bf16.hpp.
max_exponent
int std::numeric_limits< ein::bf16 >::max_exponent = 128 static constexpr
Definition at line 167 of file bf16.hpp.
max_exponent10
int std::numeric_limits< ein::bf16 >::max_exponent10 = 38 static constexpr
Definition at line 168 of file bf16.hpp.
min_exponent
int std::numeric_limits< ein::bf16 >::min_exponent = -125 static constexpr
Definition at line 165 of file bf16.hpp.
min_exponent10
int std::numeric_limits< ein::bf16 >::min_exponent10 = -37 static constexpr
Definition at line 166 of file bf16.hpp.
radix
int std::numeric_limits< ein::bf16 >::radix = 2 static constexpr
Definition at line 156 of file bf16.hpp.
round_style
float_round_style std::numeric_limits< ein::bf16 >::round_style = round_to_nearest static constexpr
Definition at line 195 of file bf16.hpp.
tinyness_before
bool std::numeric_limits< ein::bf16 >::tinyness_before = false static constexpr
Definition at line 194 of file bf16.hpp.
traps
bool std::numeric_limits< ein::bf16 >::traps = false static constexpr
Definition at line 193 of file bf16.hpp.
The documentation for this class was generated from the following file:
bf16.hpp