ein: ein::static_c_string Class Reference
ein::static_c_string Class Reference export
module ein.static_string
Public Types
using traits_type = std::char_traits<char>
using value_type = char
using pointer = char *
using const_pointer = char const *
using reference = char &
using const_reference = char const &
using const_iterator = char const *
using iterator = const_iterator
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using reverse_iterator = const_reverse_iterator
using size_type = std::size_t
using difference_type = std::ptrdiff_t
Public Member Functions
constructors
constexpr static_c_string () noexcept=default
constexpr static_c_string (static_c_string const &) noexcept=default
constexpr static_c_string (static_c_string &&) noexcept=default
constexpr static_c_string (static_string x) noexcept
assignment
ein_reinitializes constexpr static_c_string & operator= (static_c_string const &) noexcept=default
ein_reinitializes constexpr static_c_string & operator= (static_c_string &&) noexcept=default
conversion
constexpr operator const char * () const noexcept
constexpr operator static_string () const noexcept
constexpr const char * data () const noexcept
iterators
constexpr auto begin () const noexcept
O(1)
constexpr auto end () const noexcept
constexpr auto cbegin () const noexcept
O(1)
constexpr auto cend () const noexcept
O(1)
constexpr auto rbegin () const noexcept
O(n)
constexpr auto rend () const noexcept
O(1)
constexpr auto crbegin () const noexcept
O(n)
constexpr auto crend () const noexcept
O(1)
Private Attributes
const char * p
Friends
void swap (static_c_string &x, static_c_string &y) noexcept
comparison
constexpr friend bool operator== (static_c_string x, static_c_string y) noexcept
constexpr friend bool operator!= (static_c_string x, static_c_string y) noexcept
Detailed Description
Definition at line 250 of file static_string.cppm.
Member Typedef Documentation
const_iterator
using ein::static_c_string::const_iterator = char const *
Definition at line 260 of file static_string.cppm.
const_pointer
using ein::static_c_string::const_pointer = char const *
Definition at line 257 of file static_string.cppm.
const_reference
using ein::static_c_string::const_reference = char const &
Definition at line 259 of file static_string.cppm.
const_reverse_iterator
using ein::static_c_string::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 262 of file static_string.cppm.
difference_type
using ein::static_c_string::difference_type = std::ptrdiff_t
Definition at line 265 of file static_string.cppm.
iterator
using ein::static_c_string::iterator = const_iterator
Definition at line 261 of file static_string.cppm.
pointer
using ein::static_c_string::pointer = char *
Definition at line 256 of file static_string.cppm.
reference
using ein::static_c_string::reference = char &
Definition at line 258 of file static_string.cppm.
reverse_iterator
using ein::static_c_string::reverse_iterator = const_reverse_iterator
Definition at line 263 of file static_string.cppm.
size_type
using ein::static_c_string::size_type = std::size_t
Definition at line 264 of file static_string.cppm.
traits_type
using ein::static_c_string::traits_type = std::char_traits<char>
Definition at line 254 of file static_string.cppm.
value_type
using ein::static_c_string::value_type = char
Definition at line 255 of file static_string.cppm.
Constructor & Destructor Documentation
static_c_string() [1/4]
ein::static_c_string::static_c_string () constexpr default noexcept [[always_inline]]
static_c_string() [2/4]
ein::static_c_string::static_c_string (static_c_string const &) constexpr default noexcept [[always_inline]]
static_c_string() [3/4]
ein::static_c_string::static_c_string (static_c_string &&) constexpr default noexcept [[always_inline]]
static_c_string() [4/4]
ein::static_c_string::static_c_string (static_string x) inline constexpr noexcept [[always_inline]]
Definition at line 280 of file static_string.cppm.
: p(x.data()) {}
Member Function Documentation
begin()
auto ein::static_c_string::begin () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
O(1)
Definition at line 321 of file static_string.cppm.
{ return p; }
References p.
Referenced by crend(), and rend().
cbegin()
auto ein::static_c_string::cbegin () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
O(1)
Definition at line 328 of file static_string.cppm.
{ return p; }
References p.
cend()
auto ein::static_c_string::cend () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[pure]]
O(1)
Definition at line 332 of file static_string.cppm.
{ return p + strlen(p); }
References p.
crbegin()
auto ein::static_c_string::crbegin () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[pure]]
O(n)
Definition at line 344 of file static_string.cppm.
{ return std::reverse_iterator<const char *>(end()); }
References end().
crend()
auto ein::static_c_string::crend () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[pure]]
O(1)
Definition at line 348 of file static_string.cppm.
{ return std::reverse_iterator<const char *>(begin()); }
References begin().
data()
const char * ein::static_c_string::data () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[pure]] [[artificial]]
Definition at line 303 of file static_string.cppm.
{ return p; }
References p.
end()
auto ein::static_c_string::end () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[pure]]
Definition at line 324 of file static_string.cppm.
{ return p + strlen(p); }
References p.
Referenced by crbegin(), and rbegin().
operator const char *()
ein::static_c_string::operator const char * () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[pure]] [[artificial]]
Definition at line 297 of file static_string.cppm.
{ return p; }
References p.
operator static_string()
ein::static_c_string::operator static_string () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[pure]] [[artificial]]
Definition at line 300 of file static_string.cppm.
{ return string_view(p); }
References p.
operator=() [1/2]
ein_reinitializes constexpr static_c_string & ein::static_c_string::operator= (static_c_string &&) constexpr default noexcept [[always_inline]]
operator=() [2/2]
ein_reinitializes constexpr static_c_string & ein::static_c_string::operator= (static_c_string const &) constexpr default noexcept [[always_inline]]
rbegin()
auto ein::static_c_string::rbegin () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[pure]]
O(n)
Definition at line 336 of file static_string.cppm.
{ return std::reverse_iterator<const char *>(end()); }
References end().
rend()
auto ein::static_c_string::rend () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[pure]]
O(1)
Definition at line 340 of file static_string.cppm.
{ return std::reverse_iterator<const char *>(begin()); }
References begin().
Friends And Related Symbol Documentation
operator!=
friend bool operator!= (static_c_string x, static_c_string y) friend [[nodiscard]] [[always_inline]] [[pure]] [[artificial]]
Definition at line 313 of file static_string.cppm.
{ return x.p != y.p; }
operator==
friend bool operator== (static_c_string x, static_c_string y) friend [[nodiscard]] [[always_inline]] [[pure]] [[artificial]]
Definition at line 310 of file static_string.cppm.
{ return x.p == y.p; }
swap
void swap (static_c_string & x, static_c_string & y) friend [[always_inline]]
Definition at line 353 of file static_string.cppm.
{
    using std::swap;
    swap(x.p,y.p);
  }
Member Data Documentation
p
const char* ein::static_c_string::p private
Definition at line 251 of file static_string.cppm.
Referenced by begin(), cbegin(), cend(), data(), end(), operator const char *(), and operator static_string().
The documentation for this class was generated from the following file:
static_string.cppm