ein: std::numeric_limits< ein::fp16 > Class Reference
std::numeric_limits< ein::fp16 > Class Reference
#include <fp16.hpp>
Static Public Member Functions
static constexpr ein::fp16 min () noexcept
static constexpr ein::fp16 max () noexcept
static constexpr ein::fp16 lowest () noexcept
static constexpr ein::fp16 epsilon () noexcept
static constexpr ein::fp16 round_error () noexcept
static constexpr ein::fp16 infinity () noexcept
static constexpr ein::fp16 quiet_NaN () noexcept
static constexpr ein::fp16 signaling_NaN () noexcept
static constexpr ein::fp16 denorm_min () noexcept
Static Public Attributes
static constexpr bool is_specialized = true
static constexpr int digits = 11
static constexpr int digits10 = 3
static constexpr bool is_signed = true
static constexpr bool is_integer = false
static constexpr bool is_exact = false
static constexpr int radix = 2
static constexpr int min_exponent = -13
static constexpr int min_exponent10 = -4
static constexpr int max_exponent = 16
static constexpr int max_exponent10 = 4
static constexpr bool has_infinity = true
static constexpr bool has_quiet_NaN = true
static constexpr bool has_signaling_NaN = true
static constexpr float_denorm_style has_denorm = denorm_absent
static constexpr bool has_denorm_loss = false
static constexpr bool is_iec559 = false
static constexpr bool is_bounded = false
static constexpr bool is_modulo = false
static constexpr bool traps = false
static constexpr bool tinyness_before = false
static constexpr float_round_style round_style = round_to_nearest
Detailed Description
Definition at line 123 of file fp16.hpp.
Member Function Documentation
denorm_min()
static constexpr ein::fp16 std::numeric_limits< ein::fp16 >::denorm_min () inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 174 of file fp16.hpp.
{
      return ein::fp16::from_bits(0);
    }
References ein::fp16::from_bits().
epsilon()
static constexpr ein::fp16 std::numeric_limits< ein::fp16 >::epsilon () inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 145 of file fp16.hpp.
{
      return ein::fp16::from_bits(0x1200);
    }
References ein::fp16::from_bits().
infinity()
static constexpr ein::fp16 std::numeric_limits< ein::fp16 >::infinity () inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 162 of file fp16.hpp.
{
      return ein::fp16::from_bits(0x7C00);
    }
References ein::fp16::from_bits().
lowest()
static constexpr ein::fp16 std::numeric_limits< ein::fp16 >::lowest () inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 135 of file fp16.hpp.
{
      return ein::fp16::from_bits(0xFBFF);
    }
References ein::fp16::from_bits().
max()
static constexpr ein::fp16 std::numeric_limits< ein::fp16 >::max () inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 131 of file fp16.hpp.
{
      return ein::fp16::from_bits(0x7BFF);
    }
References ein::fp16::from_bits().
min()
static constexpr ein::fp16 std::numeric_limits< ein::fp16 >::min () inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 127 of file fp16.hpp.
{
      return ein::fp16::from_bits(0x0200);
    }
References ein::fp16::from_bits().
quiet_NaN()
static constexpr ein::fp16 std::numeric_limits< ein::fp16 >::quiet_NaN () inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 166 of file fp16.hpp.
{
      return ein::fp16::from_bits(0x7FFF);
    }
References ein::fp16::from_bits().
round_error()
static constexpr ein::fp16 std::numeric_limits< ein::fp16 >::round_error () inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 149 of file fp16.hpp.
{
      return ein::fp16::from_bits(0x3C00);
    }
References ein::fp16::from_bits().
signaling_NaN()
static constexpr ein::fp16 std::numeric_limits< ein::fp16 >::signaling_NaN () inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 170 of file fp16.hpp.
{
      return ein::fp16::from_bits(0x7DFF);
    }
References ein::fp16::from_bits().
Member Data Documentation
digits
int std::numeric_limits< ein::fp16 >::digits = 11 static constexpr
Definition at line 138 of file fp16.hpp.
digits10
int std::numeric_limits< ein::fp16 >::digits10 = 3 static constexpr
Definition at line 139 of file fp16.hpp.
has_denorm
float_denorm_style std::numeric_limits< ein::fp16 >::has_denorm = denorm_absent static constexpr
Definition at line 159 of file fp16.hpp.
has_denorm_loss
bool std::numeric_limits< ein::fp16 >::has_denorm_loss = false static constexpr
Definition at line 160 of file fp16.hpp.
has_infinity
bool std::numeric_limits< ein::fp16 >::has_infinity = true static constexpr
Definition at line 156 of file fp16.hpp.
has_quiet_NaN
bool std::numeric_limits< ein::fp16 >::has_quiet_NaN = true static constexpr
Definition at line 157 of file fp16.hpp.
has_signaling_NaN
bool std::numeric_limits< ein::fp16 >::has_signaling_NaN = true static constexpr
Definition at line 158 of file fp16.hpp.
is_bounded
bool std::numeric_limits< ein::fp16 >::is_bounded = false static constexpr
Definition at line 178 of file fp16.hpp.
is_exact
bool std::numeric_limits< ein::fp16 >::is_exact = false static constexpr
Definition at line 142 of file fp16.hpp.
is_iec559
bool std::numeric_limits< ein::fp16 >::is_iec559 = false static constexpr
Definition at line 177 of file fp16.hpp.
is_integer
bool std::numeric_limits< ein::fp16 >::is_integer = false static constexpr
Definition at line 141 of file fp16.hpp.
is_modulo
bool std::numeric_limits< ein::fp16 >::is_modulo = false static constexpr
Definition at line 179 of file fp16.hpp.
is_signed
bool std::numeric_limits< ein::fp16 >::is_signed = true static constexpr
Definition at line 140 of file fp16.hpp.
is_specialized
bool std::numeric_limits< ein::fp16 >::is_specialized = true static constexpr
Definition at line 125 of file fp16.hpp.
max_exponent
int std::numeric_limits< ein::fp16 >::max_exponent = 16 static constexpr
Definition at line 154 of file fp16.hpp.
max_exponent10
int std::numeric_limits< ein::fp16 >::max_exponent10 = 4 static constexpr
Definition at line 155 of file fp16.hpp.
min_exponent
int std::numeric_limits< ein::fp16 >::min_exponent = -13 static constexpr
Definition at line 152 of file fp16.hpp.
min_exponent10
int std::numeric_limits< ein::fp16 >::min_exponent10 = -4 static constexpr
Definition at line 153 of file fp16.hpp.
radix
int std::numeric_limits< ein::fp16 >::radix = 2 static constexpr
Definition at line 143 of file fp16.hpp.
round_style
float_round_style std::numeric_limits< ein::fp16 >::round_style = round_to_nearest static constexpr
Definition at line 182 of file fp16.hpp.
tinyness_before
bool std::numeric_limits< ein::fp16 >::tinyness_before = false static constexpr
Definition at line 181 of file fp16.hpp.
traps
bool std::numeric_limits< ein::fp16 >::traps = false static constexpr
Definition at line 180 of file fp16.hpp.
The documentation for this class was generated from the following file:
fp16.hpp