ARG HASH
FROM ghcr.io/ekmett/ein:${HASH}
ARG BASE_IMAGE="ekmett/ein:latest"
ARG HOST_UID

# Create a non-root user
RUN useradd -u ${HOST_UID} -m -s /bin/bash -d /home/runner -s /bin/bash runner
# RUN echo "runner ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# set the default user
USER runner
WORKDIR /home/runner
ENV HOME=/home/runner
LABEL org.opencontainers.image.description local build container for https://github.com/ekmett/ein.git
