var group__attributes =
[
    [ "Attribute Detection", "group__attribute__detection.html", "group__attribute__detection" ],
    [ "Inlining Control", "group__inlining__attributes.html", "group__inlining__attributes" ],
    [ "Function Multi-Versioning", "group__multiversioning__attributes.html", "group__multiversioning__attributes" ],
    [ "Calling Conventions", "group__calling__convention__attributes.html", "group__calling__convention__attributes" ],
    [ "Linkage Control", "group__linkage__attributes.html", "group__linkage__attributes" ],
    [ "Typestate Analysis", "group__typestate__analysis.html", "group__typestate__analysis" ],
    [ "Thread Safety", "group__thread__safety__attributes.html", "group__thread__safety__attributes" ],
    [ "Handles", "group__handle__attributes.html", "group__handle__attributes" ],
    [ "Aliasing Control", "group__aliasing__attributes.html", "group__aliasing__attributes" ],
    [ "Initialization", "group__initialization__attributes.html", "group__initialization__attributes" ],
    [ "Purity", "group__purity__attributes.html", "group__purity__attributes" ],
    [ "Memory Alignment", "group__alignment__attributes.html", "group__alignment__attributes" ],
    [ "String Safety", "group__string__safety__attributes.html", "group__string__safety__attributes" ],
    [ "Object Lifetimes", "group__lifetime__attributes.html", "group__lifetime__attributes" ],
    [ "Memory Allocation", "group__allocation__attributes.html", "group__allocation__attributes" ],
    [ "Control Flow", "group__control__flow__attributes.html", "group__control__flow__attributes" ],
    [ "Null Safety", "group__null__safety__attributes.html", "group__null__safety__attributes" ],
    [ "CUDA", "group__cuda__attributes.html", "group__cuda__attributes" ],
    [ "Loops", "group__loop__attributes.html", "group__loop__attributes" ],
    [ "Performance Constraints", "group__performance__constraint__attributes.html", "group__performance__constraint__attributes" ],
    [ "attributes.hpp", "attributes_8hpp.html", null ],
    [ "config.hpp", "config_8hpp.html", null ]
];