var group__attributes =
[
    [ "Calling Conventions", "group__calling__convention__attributes.html", "group__calling__convention__attributes" ],
    [ "Attribute Detection", "group__attribute__detection.html", "group__attribute__detection" ],
    [ "Purity", "group__purity__attributes.html", "group__purity__attributes" ],
    [ "Object Lifetimes", "group__lifetime__attributes.html", "group__lifetime__attributes" ],
    [ "Inlining Control", "group__inlining__attributes.html", "group__inlining__attributes" ],
    [ "Linkage Control", "group__linkage__attributes.html", "group__linkage__attributes" ],
    [ "Initialization", "group__initialization__attributes.html", "group__initialization__attributes" ],
    [ "Control Flow", "group__control__flow__attributes.html", "group__control__flow__attributes" ],
    [ "CUDA", "group__cuda__attributes.html", "group__cuda__attributes" ],
    [ "Handles", "group__handle__attributes.html", "group__handle__attributes" ],
    [ "Memory Alignment", "group__alignment__attributes.html", "group__alignment__attributes" ],
    [ "Memory Allocation", "group__allocation__attributes.html", "group__allocation__attributes" ],
    [ "Null Safety", "group__null__safety__attributes.html", "group__null__safety__attributes" ],
    [ "Performance Constraints", "group__performance__constraint__attributes.html", "group__performance__constraint__attributes" ],
    [ "String Safety", "group__string__safety__attributes.html", "group__string__safety__attributes" ],
    [ "Function Multi-Versioning", "group__target__attributes.html", "group__target__attributes" ],
    [ "Thread Safety", "group__thread__safety__attributes.html", "group__thread__safety__attributes" ],
    [ "Typestate Analysis", "group__typestate__analysis.html", "group__typestate__analysis" ],
    [ "calling_conventions.hpp", "calling__conventions_8hpp.html", null ],
    [ "common.hpp", "common_8hpp.html", null ],
    [ "control_flow.hpp", "control__flow_8hpp.html", null ],
    [ "cuda.hpp", "cuda_8hpp.html", null ],
    [ "handles.hpp", "handles_8hpp.html", null ],
    [ "memory.hpp", "attributes_2memory_8hpp.html", null ],
    [ "null_safety.hpp", "null__safety_8hpp.html", null ],
    [ "performance_constraints.hpp", "performance__constraints_8hpp.html", null ],
    [ "strings.hpp", "strings_8hpp.html", null ],
    [ "targets.hpp", "targets_8hpp.html", null ],
    [ "thread_safety.hpp", "thread__safety_8hpp.html", null ],
    [ "typestate.hpp", "typestate_8hpp.html", null ],
    [ "config.hpp", "config_8hpp.html", null ]
];