ein: SIMD
SIMD
Modules
module ein.simd
module ein.simd_data
Files
file simd.cppm
file simd_data.cppm
Concepts
concept ein::simd_type
recognizes any valid simd type
concept ein::has_simd_type
ein::simd_data_t<T,N> is defined
concept ein::has_builtin_convertvector
can we convert simd_data_t<U,N> -> simd_data_t<T,N> automatically using gcc vector extensions?
concept ein::simd_builtin
is this type one of the types that is handed well automatically by clang/gcc vector extensions?
concept ein::has_mmask
Do we want to use AVX512's notion of an _mmask8, _mmask16, _mmask32, or _mmask64 for masking operations.
Classes
struct ein::simd< T, N >
simd primitive definition
struct std::tuple_size< ein::simd< T, N > >
struct std::tuple_element< I, ein::simd< T, N > >
needed to support for std::apply
Typedefs
template<typename T , size_t N>
using ein::simd_data_t = T __attribute__((__vector_size__(N*sizeof(T)),__aligned__(N*sizeof(T))))
template<typename T , size_t N>
using ein::simd_intrinsic_t
Returns the Intel intrinsic type associated with a simd register full of N values of type T.
template<size_t N>
using ein::mmask_t
If AVX512 is enabled returns the type of an n-bit mmask.
template<typename T , size_t N>
using ein::simd_mask_t
What type of mask should I use?
Functions
__m128 ein::cast_ps (__m128i a) noexcept
__m128 ein::cast_ps (__m128 a) noexcept
__m256 ein::cast_ps (__m256i a) noexcept
__m256 ein::cast_ps (__m256 a) noexcept
__m128d ein::cast_pd (__m128i a) noexcept
__m128d ein::cast_pd (__m128d a) noexcept
__m256d ein::cast_pd (__m256i a) noexcept
__m256d ein::cast_pd (__m256d a) noexcept
__m128i ein::cast_si (__m128 a) noexcept
__m128i ein::cast_si (__m128d a) noexcept
__m128i ein::cast_si (__m128i a) noexcept
__m256i ein::cast_si (__m256 a) noexcept
__m256i ein::cast_si (__m256d a) noexcept
__m256i ein::cast_si (__m256i a) noexcept
__m512 ein::cast_ps (__m512i a) noexcept
__m512d ein::cast_pd (__m512i a) noexcept
__m512 ein::cast_ps (__m512 a) noexcept
__m512d ein::cast_pd (__m512d a) noexcept
__m512i ein::cast_si (__m512 a) noexcept
__m512i ein::cast_si (__m512d a) noexcept
__m512i ein::cast_si (__m512i a) noexcept
Variables
constexpr size_t ein::max_simd_size = 64
largest simd register width supported on this platform in bytes
argument deduction
template<typename T , size_t N>
requires (has_simd_type<T,N> && (N % sizeof(T) == 0))
ein::simd (T __attribute((__vector_size__(N)))) -> simd< T, N/sizeof(T)>
guidance when loading data from clang/gcc vector extensions
template<typename ... Args>
requires has_simd_type<std::common_type<Args...>, sizeof...(Args)>
ein::simd (Args &&...) -> simd< std::common_type< Args... >, sizeof...(Args)>
guidance for loading from arguments
template<typename T >
requires has_simd_type<T,max_simd_size/sizeof(T)>
ein::simd (T) -> simd< T, has_simd_type< T, max_simd_size/sizeof(T)> >
default to max simd size for broadcast
loads
template<std::size_t N>
auto ein::load (auto const *data) noexcept -> simd< std::remove_cvref_t< decltype(*data)>, N >
load data from aligned memory
template<std::size_t N>
auto ein::loadu (auto const *data) noexcept -> simd< std::remove_cvref_t< decltype(*data)>, N >
load data from unaligned memory
template<std::size_t N>
auto ein::lddqu (auto const *data) noexcept -> simd< std::remove_cvref_t< decltype(*data)>, N >
load data from unaligned memory, optimized for crossing cachelines (legacy approach)
template<std::size_t N>
auto ein::stream_load (auto const *data) noexcept -> simd< std::remove_cvref_t< decltype(*data)>, N >
stream data from memory non-temporally, bypassing cache
shuffles
template<size_t ... is>
auto ein::shuffle (simd_type auto x)
create a new simd register with contents drawn from this one
template<size_t ... is>
auto ein::shuffle (simd_type auto x, simd_type auto y)
create a new simd register with contents drawn from these two
Detailed Description
Class Documentation
ein::simd
struct ein::simd
template<typename T, size_t N>
requires (has_simd_type<T,N>)
struct ein::simd< T, N >
simd primitive definition
Definition at line 57 of file simd.cppm.
Public Member Functions
constructors
constexpr simd () noexcept=default
default initialization
constexpr simd (simd const &) noexcept=default
copy construction
constexpr simd (simd &&) noexcept=default
move construction
template<std::convertible_to< T > ... Args>
requires (sizeof...(Args) == N)
constexpr simd (Args &&... args) noexcept
array initialization
constexpr simd (T value) noexcept
broadcast construction
constexpr simd (data_t const &data) noexcept
copy construction from clang/gcc vector intrinsics
constexpr simd (data_t &&data) noexcept
move construction from clang/gcc vector intrinsics
constexpr simd (std::initializer_list< T > init)
initialize the first init .size values from an initializer_list TODO: use a masked unaligned load
constexpr simd (intrinsic_t const &data) noexcept
copy construct from the corresponding intel intrinsic type (if different than the gcc/clang one)
constexpr simd (intrinsic_t &&data) noexcept
move construct from the corresponding intel intrinsic type (if different than the gcc/clang one)
assignments
ein_reinitializes constexpr simd & operator= (simd &&) noexcept=default
ein_reinitializes constexpr simd & operator= (simd const &) noexcept=default
template<typename U >
requires (!std::is_same_v<U,T> && has_builtin_convertvector<U,T,N>)
ein_reinitializes constexpr simd & operator= (simd_t< U > other) noexcept
automatic conversion for types supported by __builtin_convertvector
intel compatibility
constexpr operator intrinsic_t & () noexcept
provide compatibility with Intel intrinsics by freely using this as simd_intrinsic_t<T,N> &
constexpr operator intrinsic_t const & () const noexcept
provide compatibility with Intel intrinsics by freely using this as simd_intrinsic_t<T,N> const &
constexpr intrinsic_t & it () noexcept
provide compatibility with Intel intrinsics by freely using this as simd_intrinsic_t<T,N> &
constexpr intrinsic_t const & it () const noexcept
provide compatibility with Intel intrinsics by freely using this as simd_intrinsic_t<T,N> const &
iterable
constexpr T & operator[] (std::size_t i) noexcept
access the element in the i th lane
constexpr T const & operator[] (std::size_t i) const noexcept
access the element in the i th lane
constexpr T * begin () noexcept
start iterator
constexpr T * end () noexcept
end iterator
constexpr T const * cbegin () const noexcept
const start iterator
constexpr T const * cend () const noexcept
const end iterator
constexpr T const * begin () const noexcept
const start iterator
constexpr T const * end () const noexcept
const end iterator
constexpr std::reverse_iterator< T * > rbegin () noexcept
reverse start iterator
constexpr std::reverse_iterator< T * > rend () noexcept
reverse end iterator
constexpr std::reverse_iterator< const T * > crbegin () const noexcept
const reverse start iterator
constexpr std::reverse_iterator< const T * > crend () const noexcept
const reverse end iterator
constexpr std::reverse_iterator< const T * > rbegin () const noexcept
const reverse start iterator
constexpr std::reverse_iterator< const T * > rend () const noexcept
const reverse end iterator
shuffles
template<size_t ... is>
requires (((is < N) && ... && has_simd_type<T,sizeof...(is)>) && requires (data_t x) { simd<T,sizeof...(is)>(__builtin_shufflevector(x, is...)); })
constexpr simd< T, sizeof...(is)> shuffle () noexcept
shuffle selected elements to produce a new simd register
template<size_t ... is>
requires (((is < N*2) && ... && has_simd_type<T,sizeof...(is)>) && requires (data_t x) { simd<T,sizeof...(is)>(__builtin_shufflevector(x, x, is...)); })
constexpr simd< T, sizeof...(is)> shuffle (simd< T, N > b) noexcept
Use elements taken from this and another simd register to construct another. If an index i in is is less than N, it draw from this, otherwise it draws from the i - Nth position in b.
Static Public Member Functions
loads
static constexpr simd load (T const *p) noexcept
static constexpr simd loadu (T const *p) noexcept
static constexpr simd lddqu (T const *p) noexcept
static constexpr simd stream_load (T const *p) noexcept
Public Attributes
data_t data
Private Types
using data_t = simd_data_t<T,N>
using mask_t = simd_mask_t<T,N>
using intrinsic_t = simd_intrinsic_t<T,N>
template<typename U >
using simd_t = simd<U,N>
template<typename U >
using cast_t = simd<U,N*sizeof(T)/sizeof(U)>
using value_type = T
Static Private Attributes
static constexpr size_t bytesize = N*sizeof(T)
static constexpr size_t size = N
Friends
destructuring
template<size_t I>
requires (I < N)
constexpr T & get (simd &s) noexcept
enables destructuring reference
template<size_t I>
requires (I < N)
constexpr T const & get (simd const &s) noexcept
enables destructuring constant reference
template<size_t I>
requires (I < N)
constexpr T && get (simd &&s) noexcept
enable destructuring move
comparisons
constexpr mask_t operator< (simd x, simd y) noexcept
constexpr mask_t operator> (simd x, simd y) noexcept
constexpr mask_t operator<= (simd x, simd y) noexcept
constexpr mask_t operator>= (simd x, simd y) noexcept
constexpr mask_t operator== (simd x, simd y) noexcept
constexpr mask_t operator!= (simd x, simd y) noexcept
constexpr mask_t operator< (simd a, simd b) noexcept
constexpr mask_t operator> (simd a, simd b) noexcept
constexpr mask_t operator<= (simd a, simd b) noexcept
constexpr mask_t operator>= (simd a, simd b) noexcept
constexpr mask_t operator== (simd a, simd b) noexcept
constexpr mask_t operator!= (simd a, simd b) noexcept
template<CMP imm8>
requires one_of_t<T,float,double> && (size_t(imm8) < max_fp_comparison_predicate)
constexpr mask_t cmp (simd a, simd b) noexcept
template<CMPINT imm8>
requires one_of_t<T,uint8_t,int8_t,uint16_t,int16_t,uint32_t,int32_t,uint64_t,int64_t> && (size_t(imm8) < 8uz)
constexpr mask_t cmpint (simd a, simd b) noexcept
constexpr mask_t operator== (simd a, simd b) noexcept
constexpr mask_t operator/= (simd a, simd b) noexcept
constexpr mask_t operator< (simd a, simd b) noexcept
constexpr mask_t operator<= (simd a, simd b) noexcept
constexpr mask_t operator> (simd a, simd b) noexcept
constexpr mask_t operator>= (simd a, simd b) noexcept
stores
constexpr void store (T *p, simd x) noexcept
constexpr void storeu (T *p, simd x) noexcept
constexpr void stream (T *p, simd x) noexcept
scalef
constexpr simd scalef (simd x, simd y) noexcept
data movement
constexpr void swap (simd &x, simd &y) noexcept
operators
constexpr simd & operator+= (simd other) noexcept
constexpr simd & operator-= (simd other) noexcept
constexpr simd & operator*= (simd other) noexcept
constexpr simd & operator/= (simd other) noexcept
constexpr simd & operator&= (simd other) noexcept
constexpr simd & operator|= (simd other) noexcept
constexpr simd & operator^= (simd other) noexcept
constexpr simd operator+ () const noexcept
constexpr simd operator- () const noexcept
constexpr simd & operator-- () noexcept
--x
constexpr simd operator-- (int) noexcept
x--
constexpr simd & operator++ () noexcept
++x
constexpr simd operator++ (int) noexcept
x++
template<size_t K>
requires requires (data_t a) { a >>= static_cast<T>(K); }
constexpr simd & operator>>= (imm_t< K >) noexcept
self-shift right by an immediate value
constexpr simd & operator>>= (T y) noexcept
self-shift right by a scalar
constexpr simd & operator>>= (simd y) noexcept
self-shift right elementwise
template<size_t K>
requires requires (data_t x) { x <<= K; }
constexpr simd & operator<<= (imm_t< K >) noexcept
self-shift left by an immediate constant
constexpr simd & operator<<= (T y) noexcept
self-shift left by a scalar
constexpr simd & operator<<= (simd y) noexcept
self-shift left elementwise
constexpr simd operator+ (simd x, simd y) noexcept
constexpr simd operator- (simd x, simd y) noexcept
constexpr simd operator* (simd x, simd y) noexcept
constexpr simd operator/ (simd x, simd y) noexcept
template<typename U >
requires requires (data_t a, data_t b) { a & b; }
constexpr simd operator& (simd x, simd y) noexcept
template<typename U >
requires requires (data_t a, data_t b) { a | b; }
constexpr simd operator| (simd x, simd y) noexcept
constexpr simd operator^ (simd x, simd y) noexcept
template<size_t K>
requires requires (data_t a) { a >> static_cast<T>(K); }
constexpr simd operator>> (simd x, imm_t< K >) noexcept
shift right by an immediate constant
constexpr simd operator>> (simd x, T y) noexcept
shift right by a scalar
constexpr simd operator>> (simd x, simd y) noexcept
shift right elementwise
template<size_t K>
requires requires (data_t a) { a << static_cast<T>(K); }
constexpr simd operator<< (simd x, imm_t< K >) noexcept
shift left by an immediate constant
constexpr simd operator<< (simd x, T y) noexcept
shift left by a scalar
constexpr simd operator<< (simd x, simd y) noexcept
shift left elementwise
Member Typedef Documentation
cast_t
template<typename T , size_t N> template<typename U > using ein::simd< T, N >::cast_t = simd<U,N*sizeof(T)/sizeof(U)> private
Definition at line 68 of file simd.cppm.
data_t
template<typename T , size_t N> using ein::simd< T, N >::data_t = simd_data_t<T,N> private
Definition at line 59 of file simd.cppm.
intrinsic_t
template<typename T , size_t N> using ein::simd< T, N >::intrinsic_t = simd_intrinsic_t<T,N> private
Definition at line 61 of file simd.cppm.
mask_t
template<typename T , size_t N> using ein::simd< T, N >::mask_t = simd_mask_t<T,N> private
Definition at line 60 of file simd.cppm.
simd_t
template<typename T , size_t N> template<typename U > using ein::simd< T, N >::simd_t = simd<U,N> private
Definition at line 65 of file simd.cppm.
value_type
template<typename T , size_t N> using ein::simd< T, N >::value_type = T private
Definition at line 70 of file simd.cppm.
Constructor & Destructor Documentation
simd() [1/10]
template<typename T , size_t N> ein::simd< T, N >::simd () constexpr default noexcept [[always_inline]] [[artificial]] [[hidden]]
default initialization
simd() [2/10]
template<typename T , size_t N> ein::simd< T, N >::simd (simd< T, N > const &) constexpr default noexcept [[always_inline]] [[artificial]] [[hidden]]
copy construction
simd() [3/10]
template<typename T , size_t N> ein::simd< T, N >::simd (simd< T, N > &&) constexpr default noexcept [[always_inline]] [[artificial]] [[hidden]]
move construction
simd() [4/10]
template<typename T , size_t N> template<std::convertible_to< T > ... Args> requires (sizeof...(Args) == N) ein::simd< T, N >::simd (Args &&... args) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
array initialization
e.g. simd<float,4>{1.0,2.0,3.0,4.0}
Definition at line 95 of file simd.cppm.
  : data(std::forward<Args>(args)...) {}
simd() [5/10]
template<typename T , size_t N> ein::simd< T, N >::simd (T value) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
broadcast construction
sets every member of the simd structure to the same value
Definition at line 102 of file simd.cppm.
  : data(__extension__(data_t)(value)) {}
simd() [6/10]
template<typename T , size_t N> ein::simd< T, N >::simd (data_t const & data) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
copy construction from clang/gcc vector intrinsics
Definition at line 107 of file simd.cppm.
  : data(data) {}
simd() [7/10]
template<typename T , size_t N> ein::simd< T, N >::simd (data_t && data) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
move construction from clang/gcc vector intrinsics
Definition at line 112 of file simd.cppm.
  : data(std::move(data)) {}
simd() [8/10]
template<typename T , size_t N> ein::simd< T, N >::simd (std::initializer_list< T > init) inline constexpr [[always_inline]] [[artificial]] [[hidden]]
initialize the first init .size values from an initializer_list TODO: use a masked unaligned load
Definition at line 121 of file simd.cppm.
simd() [9/10]
template<typename T , size_t N> ein::simd< T, N >::simd (intrinsic_t const & data) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
copy construct from the corresponding intel intrinsic type (if different than the gcc/clang one)
Definition at line 132 of file simd.cppm.
  : data(reinterpret_cast<data_t>(data)) {}
simd() [10/10]
template<typename T , size_t N> ein::simd< T, N >::simd (intrinsic_t && data) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
move construct from the corresponding intel intrinsic type (if different than the gcc/clang one)
Definition at line 138 of file simd.cppm.
  : data(reinterpret_cast<data_t>(std::move(data))) {}
Member Function Documentation
begin() [1/2]
template<typename T , size_t N> T const * ein::simd< T, N >::begin () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
const start iterator
Definition at line 234 of file simd.cppm.
{ return cbegin(); }
begin() [2/2]
template<typename T , size_t N> T * ein::simd< T, N >::begin () inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
start iterator
Definition at line 218 of file simd.cppm.
{ return reinterpret_cast<T*>(&data); }
cbegin()
template<typename T , size_t N> T const * ein::simd< T, N >::cbegin () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
const start iterator
Definition at line 226 of file simd.cppm.
{ return reinterpret_cast<T const *>(&data); }
cend()
template<typename T , size_t N> T const * ein::simd< T, N >::cend () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
const end iterator
Definition at line 230 of file simd.cppm.
{ return begin() + N; }
crbegin()
template<typename T , size_t N> std::reverse_iterator< const T * > ein::simd< T, N >::crbegin () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
const reverse start iterator
Definition at line 250 of file simd.cppm.
{ return std::reverse_iterator<const T*>(cend()); }
crend()
template<typename T , size_t N> std::reverse_iterator< const T * > ein::simd< T, N >::crend () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
const reverse end iterator
Definition at line 254 of file simd.cppm.
{ return std::reverse_iterator<const T*>(cbegin()); }
end() [1/2]
template<typename T , size_t N> T const * ein::simd< T, N >::end () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
const end iterator
Definition at line 238 of file simd.cppm.
{ return cend(); }
end() [2/2]
template<typename T , size_t N> T * ein::simd< T, N >::end () inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
end iterator
Definition at line 222 of file simd.cppm.
{ return begin() + N; }
it() [1/2]
template<typename T , size_t N> intrinsic_t const & ein::simd< T, N >::it () const inline constexpr noexcept [[always_inline]] [[artificial]] [[const]] [[hidden]]
provide compatibility with Intel intrinsics by freely using this as simd_intrinsic_t<T,N> const &
Definition at line 198 of file simd.cppm.
it() [2/2]
template<typename T , size_t N> intrinsic_t & ein::simd< T, N >::it () inline constexpr noexcept [[always_inline]] [[artificial]] [[const]] [[hidden]]
provide compatibility with Intel intrinsics by freely using this as simd_intrinsic_t<T,N> &
Definition at line 190 of file simd.cppm.
lddqu()
template<typename T , size_t N> static constexpr simd ein::simd< T, N >::lddqu (T const * p) inline static constexpr noexcept [[always_inline]] [[pure]] [[artificial]]
legacy: may outperform loadu when the data crosses a cache boundary
Definition at line 999 of file simd.cppm.
{
    if consteval {
      simd result;
      for (size_t i = 0;i<N;++i)
        result[i] = p[i];
      return result;
    } else {
      EIN_SWITCH(
        _mm_loadu_ps,    _mm_loadu_pd,    _mm_lddqu_si128,
        _mm256_loadu_ps, _mm256_loadu_pd, _mm256_lddqu_si256,
        _mm512_loadu_ps, _mm512_loadu_pd, _mm512_loadu_si512
      )
    }
  }
Referenced by ein::lddqu().
load()
template<typename T , size_t N> static constexpr simd ein::simd< T, N >::load (T const * p) inline static constexpr noexcept [[always_inline]] [[pure]] [[artificial]]
Precondition
p is a pointer to memory with alignment >= N
Definition at line 966 of file simd.cppm.
{
    if consteval {
      simd result;
      for (size_t i = 0;i<N;++i)
        result[i] = p[i];
      return result;
    } else {
      EIN_SWITCH(
        _mm_load_ps,    _mm_load_pd,    _mm_load_epi32,
        _mm256_load_ps, _mm256_load_pd, _mm256_load_epi32,
        _mm512_load_ps, _mm512_load_pd, _mm512_load_epi32
      )
    }
  }
Referenced by ein::load().
loadu()
template<typename T , size_t N> static constexpr simd ein::simd< T, N >::loadu (T const * p) inline static constexpr noexcept [[always_inline]] [[pure]] [[artificial]]
Definition at line 982 of file simd.cppm.
{
    if consteval {
      simd result;
      for (size_t i = 0;i<N;++i)
        result[i] = p[i];
      return result;
    } else {
      EIN_SWITCH(
        _mm_loadu_ps,    _mm_loadu_pd,    _mm_loadu_epi32,
        _mm256_loadu_ps, _mm256_loadu_pd, _mm256_loadu_epi32,
        _mm512_loadu_ps, _mm512_loadu_pd, _mm512_loadu_epi32
      )
    }
  }
Referenced by ein::loadu().
operator intrinsic_t &()
template<typename T , size_t N> ein::simd< T, N >::operator intrinsic_t & () inline constexpr noexcept [[always_inline]] [[artificial]] [[const]] [[hidden]]
provide compatibility with Intel intrinsics by freely using this as simd_intrinsic_t<T,N> &
Definition at line 174 of file simd.cppm.
{
    if constexpr (std::is_same_v<intrinsic_t,data_t>) return data;
    else return reinterpret_cast<intrinsic_t &>(data);
  }
operator intrinsic_t const &()
template<typename T , size_t N> ein::simd< T, N >::operator intrinsic_t const & () const inline constexpr noexcept [[always_inline]] [[artificial]] [[const]] [[hidden]]
provide compatibility with Intel intrinsics by freely using this as simd_intrinsic_t<T,N> const &
Definition at line 182 of file simd.cppm.
operator&=()
template<typename T , size_t N> simd & ein::simd< T, N >::operator&= (simd< T, N > other) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
Definition at line 381 of file simd.cppm.
operator*=()
template<typename T , size_t N> simd & ein::simd< T, N >::operator*= (simd< T, N > other) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
Definition at line 350 of file simd.cppm.
operator+()
template<typename T , size_t N> simd ein::simd< T, N >::operator+ () const inline constexpr noexcept [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 421 of file simd.cppm.
operator++() [1/2]
template<typename T , size_t N> simd & ein::simd< T, N >::operator++ () inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
++x
Definition at line 458 of file simd.cppm.
operator++() [2/2]
template<typename T , size_t N> simd ein::simd< T, N >::operator++ (int) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
x++
Definition at line 467 of file simd.cppm.
operator+=()
template<typename T , size_t N> simd & ein::simd< T, N >::operator+= (simd< T, N > other) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
Definition at line 319 of file simd.cppm.
operator-()
template<typename T , size_t N> simd ein::simd< T, N >::operator- () const inline constexpr noexcept [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 428 of file simd.cppm.
operator--() [1/2]
template<typename T , size_t N> simd & ein::simd< T, N >::operator-- () inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
--x
Definition at line 439 of file simd.cppm.
operator--() [2/2]
template<typename T , size_t N> simd ein::simd< T, N >::operator-- (int) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
x--
Definition at line 448 of file simd.cppm.
operator-=()
template<typename T , size_t N> simd & ein::simd< T, N >::operator-= (simd< T, N > other) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
Definition at line 335 of file simd.cppm.
operator/=()
template<typename T , size_t N> simd & ein::simd< T, N >::operator/= (simd< T, N > other) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
Definition at line 365 of file simd.cppm.
operator<<=() [1/3]
template<typename T , size_t N> template<size_t K> requires requires (data_t x) { x <<= K; } simd & ein::simd< T, N >::operator<<= (imm_t< K >) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
self-shift left by an immediate constant
Definition at line 560 of file simd.cppm.
operator<<=() [2/3]
template<typename T , size_t N> simd & ein::simd< T, N >::operator<<= (simd< T, N > y) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
self-shift left elementwise
Definition at line 580 of file simd.cppm.
operator<<=() [3/3]
template<typename T , size_t N> simd & ein::simd< T, N >::operator<<= (T y) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
self-shift left by a scalar
Definition at line 571 of file simd.cppm.
operator=() [1/3]
template<typename T , size_t N> ein_reinitializes constexpr simd & ein::simd< T, N >::operator= (simd< T, N > &&) constexpr default noexcept [[always_inline]] [[artificial]] [[hidden]]
operator=() [2/3]
template<typename T , size_t N> ein_reinitializes constexpr simd & ein::simd< T, N >::operator= (simd< T, N > const &) constexpr default noexcept [[always_inline]] [[artificial]] [[hidden]]
operator=() [3/3]
template<typename T , size_t N> template<typename U > requires (!std::is_same_v<U,T> && has_builtin_convertvector<U,T,N>) ein_reinitializes constexpr simd & ein::simd< T, N >::operator= (simd_t< U > other) inline constexpr noexcept [[always_inline]] [[artificial]]
automatic conversion for types supported by __builtin_convertvector
Definition at line 157 of file simd.cppm.
{
    if consteval {
      for (int i=0;i<N;++i)
        data[i] = T(other.data[i]);
    } else {
      data = __builtin_convertvector(other.data,data_t);
    }
  }
operator>>=() [1/3]
template<typename T , size_t N> template<size_t K> requires requires (data_t a) { a >>= static_cast<T>(K); } simd & ein::simd< T, N >::operator>>= (imm_t< K >) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
self-shift right by an immediate value
Definition at line 532 of file simd.cppm.
operator>>=() [2/3]
template<typename T , size_t N> simd & ein::simd< T, N >::operator>>= (simd< T, N > y) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
self-shift right elementwise
Definition at line 550 of file simd.cppm.
operator>>=() [3/3]
template<typename T , size_t N> simd & ein::simd< T, N >::operator>>= (T y) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
self-shift right by a scalar
Definition at line 541 of file simd.cppm.
operator[]() [1/2]
template<typename T , size_t N> T const & ein::simd< T, N >::operator[] (std::size_t i) const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
access the element in the i th lane
Definition at line 214 of file simd.cppm.
{ return reinterpret_cast<T const *>(&data)[i]; }
operator[]() [2/2]
template<typename T , size_t N> T & ein::simd< T, N >::operator[] (std::size_t i) inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
access the element in the i th lane
Definition at line 210 of file simd.cppm.
{ return reinterpret_cast<T *>(&data)[i]; }
operator^=()
template<typename T , size_t N> simd & ein::simd< T, N >::operator^= (simd< T, N > other) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
Definition at line 413 of file simd.cppm.
operator|=()
template<typename T , size_t N> simd & ein::simd< T, N >::operator|= (simd< T, N > other) inline constexpr noexcept [[always_inline]] [[artificial]] [[hidden]]
Definition at line 397 of file simd.cppm.
rbegin() [1/2]
template<typename T , size_t N> std::reverse_iterator< const T * > ein::simd< T, N >::rbegin () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
const reverse start iterator
Definition at line 258 of file simd.cppm.
{ return crbegin(); }
rbegin() [2/2]
template<typename T , size_t N> std::reverse_iterator< T * > ein::simd< T, N >::rbegin () inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
reverse start iterator
Definition at line 242 of file simd.cppm.
{ return std::reverse_iterator<T*>(end()); }
rend() [1/2]
template<typename T , size_t N> std::reverse_iterator< const T * > ein::simd< T, N >::rend () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
const reverse end iterator
Definition at line 262 of file simd.cppm.
{ return crend(); }
rend() [2/2]
template<typename T , size_t N> std::reverse_iterator< T * > ein::simd< T, N >::rend () inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]] [[const]] [[hidden]]
reverse end iterator
Definition at line 246 of file simd.cppm.
{ return std::reverse_iterator<T*>(begin()); }
shuffle() [1/2]
template<typename T , size_t N> template<size_t ... is> requires (((is < N) && ... && has_simd_type<T,sizeof...(is)>) && requires (data_t x) { simd<T,sizeof...(is)>(__builtin_shufflevector(x, is...)); }) simd< T, sizeof...(is)> ein::simd< T, N >::shuffle () inline constexpr noexcept [[always_inline]] [[artificial]]
shuffle selected elements to produce a new simd register
Definition at line 595 of file simd.cppm.
                                { simd<T,sizeof...(is)>(__builtin_shufflevector(x, is...)); }) {
    if consteval {
      return { data[is]... };
    } else {
      return __builtin_shufflevector(data,is...);
    }
  }
shuffle() [2/2]
template<typename T , size_t N> template<size_t ... is> requires (((is < N*2) && ... && has_simd_type<T,sizeof...(is)>) && requires (data_t x) { simd<T,sizeof...(is)>(__builtin_shufflevector(x, x, is...)); }) simd< T, sizeof...(is)> ein::simd< T, N >::shuffle (simd< T, N > b) inline constexpr noexcept [[always_inline]] [[artificial]] [[pure]]
Use elements taken from this and another simd register to construct another. If an index i in is is less than N, it draw from this, otherwise it draws from the i - Nth position in b.
Definition at line 609 of file simd.cppm.
                                { simd<T,sizeof...(is)>(__builtin_shufflevector(x, x, is...)); }) {
    if consteval {
      return { (is < N ? data[is] : b[is-N])... };
    } else {
      return __builtin_shufflevector(data,b.data,is...);
    }
  }
stream_load()
template<typename T , size_t N> static constexpr simd ein::simd< T, N >::stream_load (T const * p) inline static constexpr noexcept [[always_inline]] [[pure]] [[artificial]]
Precondition
p is a pointer to memory with alignment >= N
Definition at line 1022 of file simd.cppm.
Referenced by ein::stream_load().
Friends And Related Symbol Documentation
cmp
template<typename T , size_t N> template<CMP imm8> requires one_of_t<T,float,double> && (size_t(imm8) < max_fp_comparison_predicate) mask_t cmp (simd< T, N > a, simd< T, N > b) friend
Definition at line 750 of file simd.cppm.
cmpint
template<typename T , size_t N> template<CMPINT imm8> requires one_of_t<T,uint8_t,int8_t,uint16_t,int16_t,uint32_t,int32_t,uint64_t,int64_t> && (size_t(imm8) < 8uz) mask_t cmpint (simd< T, N > a, simd< T, N > b) friend
Definition at line 797 of file simd.cppm.
get [1/3]
template<typename T , size_t N> template<size_t I> requires (I < N) T && get (simd< T, N > && s) friend [[always_inline]] [[artificial]] [[const]] [[hidden]]
enable destructuring move
auto && [x,y,z,w] = simd<float,4>(1.0,2.0,3.0,4.0);
Definition at line 301 of file simd.cppm.
get [2/3]
template<typename T , size_t N> template<size_t I> requires (I < N) T & get (simd< T, N > & s) friend [[always_inline]] [[artificial]] [[const]] [[hidden]]
enables destructuring reference
auto & [x,y,z,w] = simd<float,4>(1.0,2.0,3.0,4.0);
Definition at line 277 of file simd.cppm.
get [3/3]
template<typename T , size_t N> template<size_t I> requires (I < N) T const & get (simd< T, N > const & s) friend [[always_inline]] [[artificial]] [[const]] [[hidden]]
enables destructuring constant reference
auto const & [x,y,z,w] = simd<float,4>(1.0,2.0,3.0,4.0);
Definition at line 289 of file simd.cppm.
operator!= [1/2]
template<typename T , size_t N> mask_t operator!= (simd< T, N > a, simd< T, N > b) friend [[always_inline]] [[artificial]] [[pure]]
Definition at line 733 of file simd.cppm.
{
    EIN_COMPARE_OP(!=,ne)
  }
operator!= [2/2]
template<typename T , size_t N> mask_t operator!= (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 663 of file simd.cppm.
operator&
template<typename T , size_t N> template<typename U > requires requires (data_t a, data_t b) { a & b; } simd operator& (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 374 of file simd.cppm.
operator*
template<typename T , size_t N> simd operator* (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 343 of file simd.cppm.
operator+
template<typename T , size_t N> simd operator+ (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 312 of file simd.cppm.
operator-
template<typename T , size_t N> simd operator- (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 328 of file simd.cppm.
operator/
template<typename T , size_t N> simd operator/ (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 358 of file simd.cppm.
operator/=
template<typename T , size_t N> mask_t operator/= (simd< T, N > a, simd< T, N > b) friend [[nodiscard]] [[always_inline]] [[pure]]
Definition at line 907 of file simd.cppm.
operator< [1/3]
template<typename T , size_t N> mask_t operator< (simd< T, N > a, simd< T, N > b) friend [[always_inline]] [[artificial]] [[pure]]
Definition at line 708 of file simd.cppm.
{
    EIN_COMPARE_OP(<,lt)
  }
operator< [2/3]
template<typename T , size_t N> mask_t operator< (simd< T, N > a, simd< T, N > b) friend [[nodiscard]] [[always_inline]] [[pure]]
Definition at line 914 of file simd.cppm.
operator< [3/3]
template<typename T , size_t N> mask_t operator< (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 628 of file simd.cppm.
operator<< [1/3]
template<typename T , size_t N> template<size_t K> requires requires (data_t a) { a << static_cast<T>(K); } simd operator<< (simd< T, N > x, imm_t< K >) friend
shift left by an immediate constant
Definition at line 506 of file simd.cppm.
operator<< [2/3]
template<typename T , size_t N> simd operator<< (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
shift left elementwise
Definition at line 521 of file simd.cppm.
operator<< [3/3]
template<typename T , size_t N> simd operator<< (simd< T, N > x, T y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
shift left by a scalar
Definition at line 513 of file simd.cppm.
operator<= [1/3]
template<typename T , size_t N> mask_t operator<= (simd< T, N > a, simd< T, N > b) friend [[always_inline]] [[artificial]] [[pure]]
Definition at line 718 of file simd.cppm.
{
    EIN_COMPARE_OP(<=,le)
  }
operator<= [2/3]
template<typename T , size_t N> mask_t operator<= (simd< T, N > a, simd< T, N > b) friend [[nodiscard]] [[always_inline]] [[pure]]
Definition at line 921 of file simd.cppm.
operator<= [3/3]
template<typename T , size_t N> mask_t operator<= (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 642 of file simd.cppm.
operator== [1/3]
template<typename T , size_t N> mask_t operator== (simd< T, N > a, simd< T, N > b) friend [[always_inline]] [[artificial]] [[pure]]
Definition at line 728 of file simd.cppm.
{
    EIN_COMPARE_OP(==,eq)
  }
operator== [2/3]
template<typename T , size_t N> mask_t operator== (simd< T, N > a, simd< T, N > b) friend [[nodiscard]] [[always_inline]] [[pure]]
Definition at line 900 of file simd.cppm.
operator== [3/3]
template<typename T , size_t N> mask_t operator== (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 656 of file simd.cppm.
operator> [1/3]
template<typename T , size_t N> mask_t operator> (simd< T, N > a, simd< T, N > b) friend [[always_inline]] [[artificial]] [[pure]]
Definition at line 713 of file simd.cppm.
{
    EIN_COMPARE_OP(>,gt)
  }
operator> [2/3]
template<typename T , size_t N> mask_t operator> (simd< T, N > a, simd< T, N > b) friend [[nodiscard]] [[always_inline]] [[pure]]
Definition at line 928 of file simd.cppm.
operator> [3/3]
template<typename T , size_t N> mask_t operator> (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 635 of file simd.cppm.
operator>= [1/3]
template<typename T , size_t N> mask_t operator>= (simd< T, N > a, simd< T, N > b) friend [[always_inline]] [[artificial]] [[pure]]
Definition at line 723 of file simd.cppm.
{
    EIN_COMPARE_OP(>=,ge)
  }
operator>= [2/3]
template<typename T , size_t N> mask_t operator>= (simd< T, N > a, simd< T, N > b) friend [[nodiscard]] [[always_inline]] [[pure]]
Definition at line 935 of file simd.cppm.
operator>= [3/3]
template<typename T , size_t N> mask_t operator>= (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 649 of file simd.cppm.
operator>> [1/3]
template<typename T , size_t N> template<size_t K> requires requires (data_t a) { a >> static_cast<T>(K); } simd operator>> (simd< T, N > x, imm_t< K >) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
shift right by an immediate constant
Definition at line 478 of file simd.cppm.
operator>> [2/3]
template<typename T , size_t N> simd operator>> (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
shift right elementwise
Definition at line 494 of file simd.cppm.
operator>> [3/3]
template<typename T , size_t N> simd operator>> (simd< T, N > x, T y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
shift right by a scalar
Definition at line 486 of file simd.cppm.
operator^
template<typename T , size_t N> simd operator^ (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 406 of file simd.cppm.
operator|
template<typename T , size_t N> template<typename U > requires requires (data_t a, data_t b) { a | b; } simd operator| (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]] [[hidden]]
Definition at line 390 of file simd.cppm.
scalef
template<typename T , size_t N> simd scalef (simd< T, N > x, simd< T, N > y) friend [[always_inline]] [[artificial]] [[pure]]
Definition at line 1116 of file simd.cppm.
store
template<typename T , size_t N> void store (T * p, simd< T, N > x) friend [[always_inline]] [[artificial]] [[hidden]]
Definition at line 1064 of file simd.cppm.
{
    if consteval {
      for (size_t i = 0;i<N;++i)
        p[i] = x.data[i];
    } else {
      EIN_SWITCH(
        _mm_store_ps,    _mm_store_pd,    _mm_store_epi32,
        _mm256_store_ps, _mm256_store_pd, _mm256_store_epi32,
        _mm512_store_ps, _mm512_store_pd, _mm512_store_epi32
      )
    }
  }
storeu
template<typename T , size_t N> void storeu (T * p, simd< T, N > x) friend [[always_inline]] [[artificial]] [[hidden]]
Definition at line 1078 of file simd.cppm.
{
    if consteval {
      for (size_t i = 0;i<N;++i)
        p[i] = x.data[i];
    } else {
      EIN_SWITCH(
        _mm_store_ps,    _mm_store_pd,    _mm_store_epi32,
        _mm256_store_ps, _mm256_store_pd, _mm256_store_epi32,
        _mm512_store_ps, _mm512_store_pd, _mm512_store_epi32
      )
    }
  }
stream
template<typename T , size_t N> void stream (T * p, simd< T, N > x) friend [[always_inline]] [[artificial]] [[hidden]]
Definition at line 1092 of file simd.cppm.
{
    if consteval {
      for (size_t i = 0;i<N;++i)
        p[i] = x.data[i];
    } else {
      EIN_SWITCH(
        _mm_stream_ps,    _mm_stream_pd,    _mm_stream_si128,
        _mm256_stream_ps, _mm256_stream_pd, _mm256_stream_si256,
        _mm512_stream_ps, _mm512_stream_pd, _mm512_stream_si512
      )
    }
  }
swap
template<typename T , size_t N> void swap (simd< T, N > & x, simd< T, N > & y) friend [[always_inline]] [[artificial]]
Definition at line 1148 of file simd.cppm.
{
    if consteval {
      for (int i=0;i<N;++i)
        swap(x[i],y[i]);
    } else {
      swap(x.data,y.data);
    }
  }
Member Data Documentation
bytesize
template<typename T , size_t N> size_t ein::simd< T, N >::bytesize = N*sizeof(T) static constexpr private
Definition at line 62 of file simd.cppm.
data
template<typename T , size_t N> data_t ein::simd< T, N >::data
Definition at line 74 of file simd.cppm.
size
template<typename T , size_t N> size_t ein::simd< T, N >::size = N static constexpr private
Definition at line 71 of file simd.cppm.
std::tuple_size< ein::simd< T, N > >
struct std::tuple_size< ein::simd< T, N > >
template<typename T, size_t N>
struct std::tuple_size< ein::simd< T, N > >
Definition at line 1311 of file simd.cppm.
std::tuple_element< I, ein::simd< T, N > >
struct std::tuple_element< I, ein::simd< T, N > >
template<size_t I, typename T, size_t N>
requires (I < N)
struct std::tuple_element< I, ein::simd< T, N > >
needed to support for std::apply
Definition at line 1316 of file simd.cppm.
Class Members
typedef T type T
Typedef Documentation
mmask_t
template<size_t N> using ein::mmask_t export
If AVX512 is enabled returns the type of an n-bit mmask.
Definition at line 139 of file simd_data.cppm.
simd_data_t
template<typename T , size_t N> using ein::simd_data_t = T __attribute__((__vector_size__(N*sizeof(T)),__aligned__(N*sizeof(T)))) export
Definition at line 54 of file simd_data.cppm.
simd_intrinsic_t
template<typename T , size_t N> using ein::simd_intrinsic_t export
Returns the Intel intrinsic type associated with a simd register full of N values of type T.
this can differ from the preferred type used by clang/gcc vector extensions.
Definition at line 113 of file simd_data.cppm.
simd_mask_t
template<typename T , size_t N> using ein::simd_mask_t export
What type of mask should I use?
Definition at line 146 of file simd_data.cppm.
Function Documentation
cast_pd() [1/6]
__m128d ein::cast_pd (__m128d a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 169 of file simd_data.cppm.
{ return a; }
export ein_nodiscard ein_inline ein_const ein_artificial
__m256d cast_pd(__m256i a) noexcept { return _mm256_castsi256_pd(a); }
export ein_nodiscard ein_inline ein_const ein_artificial
__m256d cast_pd(__m256d a) noexcept { return a; }
export ein_nodiscard ein_inline ein_const ein_artificial
__m128i cast_si(__m128 a) noexcept { return _mm_castps_si128(a); }
export ein_nodiscard ein_inline ein_const ein_artificial
__m128i cast_si(__m128d a) noexcept { return _mm_castpd_si128(a); }
export ein_nodiscard ein_inline ein_const ein_artificial
__m128i cast_si(__m128i a) noexcept { return a; }
export ein_nodiscard ein_inline ein_const ein_artificial
__m256i cast_si(__m256 a) noexcept { return _mm256_castps_si256(a); }
export ein_nodiscard ein_inline ein_const ein_artificial
__m256i cast_si(__m256d a) noexcept { return _mm256_castpd_si256(a); }
export ein_nodiscard ein_inline ein_const ein_artificial
__m256i cast_si(__m256i a) noexcept { return a; }
#ifdef __AVX512F__
export ein_nodiscard ein_inline ein_const ein_artificial
__m512 cast_ps(__m512i a) noexcept { return _mm512_castsi512_ps(a); }
export ein_nodiscard ein_inline ein_const ein_artificial
__m512d cast_pd(__m512i a) noexcept { return _mm512_castsi512_pd(a); }
export ein_nodiscard ein_inline ein_const ein_artificial
__m512 cast_ps(__m512 a) noexcept { return a; }
export ein_nodiscard ein_inline ein_const ein_artificial
__m512d cast_pd(__m512d a) noexcept { return a; }
export ein_nodiscard ein_inline ein_const ein_artificial
__m512i cast_si(__m512 a) noexcept { return _mm512_castps_si512(a); }
export ein_nodiscard ein_inline ein_const ein_artificial
__m512i cast_si(__m512d a) noexcept { return _mm512_castpd_si512(a); }
export ein_nodiscard ein_inline ein_const ein_artificial
__m512i cast_si(__m512i a) noexcept { return a; }
#endif // __AVX512F__
} // namespace ein
cast_pd() [2/6]
__m128d ein::cast_pd (__m128i a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 166 of file simd_data.cppm.
cast_pd() [3/6]
__m256d ein::cast_pd (__m256d a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 175 of file simd_data.cppm.
cast_pd() [4/6]
__m256d ein::cast_pd (__m256i a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 172 of file simd_data.cppm.
cast_pd() [5/6]
__m512d ein::cast_pd (__m512d a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 207 of file simd_data.cppm.
cast_pd() [6/6]
__m512d ein::cast_pd (__m512i a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 201 of file simd_data.cppm.
cast_ps() [1/6]
__m128 ein::cast_ps (__m128 a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 157 of file simd_data.cppm.
cast_ps() [2/6]
__m128 ein::cast_ps (__m128i a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 154 of file simd_data.cppm.
cast_ps() [3/6]
__m256 ein::cast_ps (__m256 a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 163 of file simd_data.cppm.
cast_ps() [4/6]
__m256 ein::cast_ps (__m256i a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 160 of file simd_data.cppm.
cast_ps() [5/6]
__m512 ein::cast_ps (__m512 a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 204 of file simd_data.cppm.
cast_ps() [6/6]
__m512 ein::cast_ps (__m512i a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 198 of file simd_data.cppm.
cast_si() [1/9]
__m128i ein::cast_si (__m128 a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 178 of file simd_data.cppm.
cast_si() [2/9]
__m128i ein::cast_si (__m128d a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 181 of file simd_data.cppm.
cast_si() [3/9]
__m128i ein::cast_si (__m128i a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 184 of file simd_data.cppm.
cast_si() [4/9]
__m256i ein::cast_si (__m256 a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 187 of file simd_data.cppm.
cast_si() [5/9]
__m256i ein::cast_si (__m256d a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 190 of file simd_data.cppm.
cast_si() [6/9]
__m256i ein::cast_si (__m256i a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 193 of file simd_data.cppm.
cast_si() [7/9]
__m512i ein::cast_si (__m512 a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 210 of file simd_data.cppm.
cast_si() [8/9]
__m512i ein::cast_si (__m512d a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 213 of file simd_data.cppm.
cast_si() [9/9]
__m512i ein::cast_si (__m512i a) export noexcept [[nodiscard]] [[always_inline]] [[const]] [[artificial]]
Definition at line 216 of file simd_data.cppm.
lddqu()
template<std::size_t N> auto ein::lddqu (auto const * data) -> simd<std::remove_cvref_t<decltype(*data)>,N> export noexcept [[always_inline]] [[pure]] [[artificial]]
load data from unaligned memory, optimized for crossing cachelines (legacy approach)
Definition at line 1213 of file simd.cppm.
{
  using T = std::remove_cvref_t<decltype(*data)>;
  static_assert(has_simd_type<T,N>);
  return simd<T,N>::lddqu(data);
}
References ein::simd< T, N >::lddqu().
load()
template<std::size_t N> auto ein::load (auto const * data) -> simd<std::remove_cvref_t<decltype(*data)>,N> noexcept [[always_inline]] [[pure]] [[artificial]]
load data from aligned memory
Precondition
data has alignment >= N
Definition at line 1195 of file simd.cppm.
{
  using T = std::remove_cvref_t<decltype(*data)>;
  static_assert(has_simd_type<T,N>);
  return simd<T,N>::load(data);
}
References ein::simd< T, N >::load().
loadu()
template<std::size_t N> auto ein::loadu (auto const * data) -> simd<std::remove_cvref_t<decltype(*data)>,N> export noexcept [[always_inline]] [[pure]] [[artificial]]
load data from unaligned memory
Definition at line 1204 of file simd.cppm.
{
  using T = std::remove_cvref_t<decltype(*data)>;
  static_assert(has_simd_type<T,N>);
  return simd<T,N>::loadu(data);
}
References ein::simd< T, N >::loadu().
shuffle() [1/2]
template<size_t ... is> auto ein::shuffle (simd_type auto x) [[always_inline]] [[artificial]] [[pure]]
create a new simd register with contents drawn from this one
Definition at line 1252 of file simd.cppm.
{
  return x.template shuffle<is...>();
}
References ein::shuffle().
Referenced by ein::shuffle(), and ein::shuffle().
shuffle() [2/2]
template<size_t ... is> auto ein::shuffle (simd_type auto x, simd_type auto y) [[always_inline]] [[artificial]] [[pure]]
create a new simd register with contents drawn from these two
Definition at line 1259 of file simd.cppm.
{
  return x.template shuffle<is...>(y);
}
References ein::shuffle().
simd() [1/3]
template<typename ... Args> requires has_simd_type<std::common_type<Args...>, sizeof...(Args)> ein::simd (Args && ...) -> simd< std::common_type< Args... >, sizeof...(Args)> export
guidance for loading from arguments
simd() [2/3]
template<typename T , size_t N> requires (has_simd_type<T,N> && (N % sizeof(T) == 0)) ein::simd (T __attribute(__vector_size__(N))) -> simd< T, N/sizeof(T)> export
guidance when loading data from clang/gcc vector extensions
simd() [3/3]
template<typename T > requires has_simd_type<T,max_simd_size/sizeof(T)> ein::simd (T) -> simd< T, has_simd_type< T, max_simd_size/sizeof(T)> > export
default to max simd size for broadcast
Warning
this may be removed in the future.
stream_load()
template<std::size_t N> auto ein::stream_load (auto const * data) -> simd<std::remove_cvref_t<decltype(*data)>,N> export noexcept [[always_inline]] [[pure]] [[artificial]]
stream data from memory non-temporally, bypassing cache
Precondition
data has alignment >= N
Definition at line 1223 of file simd.cppm.
{
  using T = std::remove_cvref_t<decltype(*data)>;
  static_assert(has_simd_type<T,N>);
  return simd<T,N>::stream_load(data);
}
References ein::simd< T, N >::stream_load().
Variable Documentation
max_simd_size
size_t ein::max_simd_size = 64 constexpr export
largest simd register width supported on this platform in bytes
Definition at line 36 of file simd_data.cppm.