ein: std Namespace Reference
std Namespace Reference
Namespaces
namespace ranges
Classes
struct hash<::ein::basic_static_string< CharT, Traits > >
struct hash<::ein::static_c_string >
class numeric_limits< ein::fp16 >
struct tuple_element< I, ein::simd< T, N > >
needed to support for std::apply
struct tuple_size< ein::simd< T, N > >
Functions
constexpr bool std::isnan (ein::fp16 x) noexcept
template<typename T >
constexpr auto std::forward_like (auto &&x) noexcept -> forward_like_t< T, decltype(x)>
Returns a reference to x which has similar properties to T&&.
Function Documentation
isnan()
bool std::isnan (ein::fp16 x) constexpr export noexcept [[nodiscard]] [[artificial]] [[always_inline]] [[const]]
Definition at line 100 of file fp16.hpp.
{
    // Sign doesn't matter, frac not zero (infinity)
    return (x.to_bits() & 0x7FFF) > 0x7c00;
  }
Referenced by ein::cmp_ord(), ein::cmp_unord(), and ein::scalef().