ein: ein::profiling::profile< Mutex, Duration, Clock > Struct Template Reference
ein::profiling::profile< Mutex, Duration, Clock > Struct Template Reference export
module ein.profiling
Public Types
using mutex = Mutex
using duration = Duration
using clock = Clock
using event = profile_event<Duration, Clock>
Public Member Functions
profile (profile const &)=delete
profile (profile &&)=delete
profile () noexcept
~profile () noexcept
profile & operator= (profile const &)=delete
profile & operator= (profile &&)=delete
void log (event const &e) noexcept
void set_process_name (std::string name=program_invocation_short_name) noexcept
void set_thread_name (std::string const &name) noexcept
void instant (static_string name, scope s) noexcept
void counter (static_string name, json args) noexcept
void flow_start (static_string name, static_string category, static_string id) noexcept
void flow_end (std::string name, static_string cat, static_string id) noexcept
void save (std::filesystem::path filename) noexcept
Public Attributes
Mutex events_mutex
std::vector< event > events
json metadata
bool saved
std::filesystem::path filename
Friends
template<typename OStream >
OStream & operator<< (OStream &o, profile &p)
Detailed Description
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock>
struct ein::profiling::profile< Mutex, Duration, Clock >
Definition at line 121 of file profiling.cppm.
Member Typedef Documentation
clock
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> using ein::profiling::profile< Mutex, Duration, Clock >::clock = Clock
Definition at line 124 of file profiling.cppm.
duration
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> using ein::profiling::profile< Mutex, Duration, Clock >::duration = Duration
Definition at line 123 of file profiling.cppm.
event
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> using ein::profiling::profile< Mutex, Duration, Clock >::event = profile_event<Duration, Clock>
Definition at line 125 of file profiling.cppm.
mutex
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> using ein::profiling::profile< Mutex, Duration, Clock >::mutex = Mutex
Definition at line 122 of file profiling.cppm.
Constructor & Destructor Documentation
profile() [1/3]
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> ein::profiling::profile< Mutex, Duration, Clock >::profile (profile< Mutex, Duration, Clock > const &) delete
profile() [2/3]
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> ein::profiling::profile< Mutex, Duration, Clock >::profile (profile< Mutex, Duration, Clock > &&) delete
profile() [3/3]
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> ein::profiling::profile< Mutex, Duration, Clock >::profile () inline noexcept
Definition at line 136 of file profiling.cppm.
  : events_mutex()
  , events()
  , metadata(json{})
  , saved(true) {
  }
~profile()
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> ein::profiling::profile< Mutex, Duration, Clock >::~profile () inline noexcept
Definition at line 143 of file profiling.cppm.
                      {
    // TODO: complain if not saved
    if (!saved)
      spdlog::warn("Warning: unsaved profile, discarding {} event(s)", events.size());
  }
References ein::profiling::profile< Mutex, Duration, Clock >::events, and ein::profiling::profile< Mutex, Duration, Clock >::saved.
Member Function Documentation
counter()
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> void ein::profiling::profile< Mutex, Duration, Clock >::counter (static_string name, json args) inline noexcept [[always_inline]]
Definition at line 175 of file profiling.cppm.
{
    log({.name = name, .ph = event_type::counter, .args = std::move(args) });
  }
References ein::profiling::counter, and ein::profiling::profile< Mutex, Duration, Clock >::log().
flow_end()
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> void ein::profiling::profile< Mutex, Duration, Clock >::flow_end (std::string name, static_string cat, static_string id) inline noexcept [[always_inline]]
Definition at line 185 of file profiling.cppm.
{
    log({.name = std::move(name), .cat = std::move(cat), .ph = event_type::flow_end, .id = std::move(id), .bp = "e"_ss});
  }
References ein::profiling::flow_end, and ein::profiling::profile< Mutex, Duration, Clock >::log().
flow_start()
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> void ein::profiling::profile< Mutex, Duration, Clock >::flow_start (static_string name, static_string category, static_string id) inline noexcept [[always_inline]]
Definition at line 180 of file profiling.cppm.
{
    log({.name = name, .id = id, .ph = event_type::flow_start, .cat = category});
  }
References ein::profiling::flow_start, and ein::profiling::profile< Mutex, Duration, Clock >::log().
instant()
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> void ein::profiling::profile< Mutex, Duration, Clock >::instant (static_string name, scope s) inline noexcept [[always_inline]]
Definition at line 170 of file profiling.cppm.
{
    log({.name = name, .ph = event_type::instant, .s = s});
  }
References ein::profiling::instant, and ein::profiling::profile< Mutex, Duration, Clock >::log().
log()
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> void ein::profiling::profile< Mutex, Duration, Clock >::log (event const & e) inline noexcept [[always_inline]]
Definition at line 153 of file profiling.cppm.
{
    std::lock_guard<Mutex> lock(events_mutex);
    events.emplace_back(e);
    saved = false;
  }
References ein::profiling::profile< Mutex, Duration, Clock >::events, ein::profiling::profile< Mutex, Duration, Clock >::events_mutex, and ein::profiling::profile< Mutex, Duration, Clock >::saved.
Referenced by ein::profiling::profile< Mutex, Duration, Clock >::counter(), ein::profiling::profile< Mutex, Duration, Clock >::flow_end(), ein::profiling::profile< Mutex, Duration, Clock >::flow_start(), ein::profiling::profile< Mutex, Duration, Clock >::instant(), ein::profiling::scope_event< Profile >::scope_event(), ein::profiling::profile< Mutex, Duration, Clock >::set_process_name(), ein::profiling::profile< Mutex, Duration, Clock >::set_thread_name(), ein::profiling::duration_event< Profile >::start(), ein::profiling::duration_event< Profile >::stop(), and ein::profiling::scope_event< Profile >::~scope_event().
operator=() [1/2]
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> profile & ein::profiling::profile< Mutex, Duration, Clock >::operator= (profile< Mutex, Duration, Clock > &&) delete
operator=() [2/2]
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> profile & ein::profiling::profile< Mutex, Duration, Clock >::operator= (profile< Mutex, Duration, Clock > const &) delete
save()
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> void ein::profiling::profile< Mutex, Duration, Clock >::save (std::filesystem::path filename) inline noexcept [[always_inline]]
Definition at line 190 of file profiling.cppm.
{
    spdlog::info("Saving profile: {}",filename.c_str());
    std::ofstream o(filename);
    o << *this;
  }
References ein::profiling::profile< Mutex, Duration, Clock >::filename.
Referenced by ein::profiling::profile_scope< Mutex, Duration, Clock >::~profile_scope().
set_process_name()
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> void ein::profiling::profile< Mutex, Duration, Clock >::set_process_name (std::string name = program_invocation_short_name) inline noexcept [[always_inline]]
Definition at line 160 of file profiling.cppm.
{
    log({.name = "process_name"_ss, .ph = event_type::metadata, .args = { {"name",name}}});
  }
References ein::profiling::profile< Mutex, Duration, Clock >::log(), and ein::profiling::metadata.
set_thread_name()
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> void ein::profiling::profile< Mutex, Duration, Clock >::set_thread_name (std::string const & name) inline noexcept [[always_inline]]
Definition at line 165 of file profiling.cppm.
{
    log({.name = "thread_name"_ss, .ph = event_type::metadata, .args = { {"name",name}}});
  }
References ein::profiling::profile< Mutex, Duration, Clock >::log(), and ein::profiling::metadata.
Friends And Related Symbol Documentation
operator<<
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> template<typename OStream > OStream & operator<< (OStream & o, profile< Mutex, Duration, Clock > & p) friend [[always_inline]]
Definition at line 199 of file profiling.cppm.
{
    o << std::setw(2) << json(p) << std::endl;
    p.saved = true;
    return o;
  }
Member Data Documentation
events
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> std::vector<event> ein::profiling::profile< Mutex, Duration, Clock >::events
Definition at line 128 of file profiling.cppm.
Referenced by ein::profiling::profile< Mutex, Duration, Clock >::log(), and ein::profiling::profile< Mutex, Duration, Clock >::~profile().
events_mutex
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> Mutex ein::profiling::profile< Mutex, Duration, Clock >::events_mutex
Definition at line 127 of file profiling.cppm.
Referenced by ein::profiling::profile< Mutex, Duration, Clock >::log().
filename
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> std::filesystem::path ein::profiling::profile< Mutex, Duration, Clock >::filename
Definition at line 135 of file profiling.cppm.
Referenced by ein::profiling::profile< Mutex, Duration, Clock >::save().
metadata
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> json ein::profiling::profile< Mutex, Duration, Clock >::metadata
Definition at line 129 of file profiling.cppm.
saved
template<typename Mutex = std::mutex, typename Duration = std::chrono::nanoseconds, typename Clock = std::chrono::high_resolution_clock> bool ein::profiling::profile< Mutex, Duration, Clock >::saved
Definition at line 130 of file profiling.cppm.
Referenced by ein::profiling::profile< Mutex, Duration, Clock >::log(), and ein::profiling::profile< Mutex, Duration, Clock >::~profile().
The documentation for this struct was generated from the following file:
profiling.cppm