ein: ein::fp16 Struct Reference
ein::fp16 Struct Reference export
module ein.fp16
#include <fp16.hpp>
Public Member Functions
constexpr fp16 () noexcept=default
constexpr fp16 (float content) noexcept
constexpr operator float () const noexcept
constexpr uint16_t to_bits () const noexcept
Static Public Member Functions
static constexpr fp16 from_bits (uint16_t data) noexcept
Public Attributes
_Float16 content
Friends
constexpr bool operator== (fp16 x, fp16 y) noexcept
ein_artificialein_const friend constexpr bool operator!= (fp16 x, fp16 y) noexcept
constexpr std::partial_ordering operator<=> (fp16 x, fp16 y) noexcept
constexpr bool operator< (fp16 x, fp16 y) noexcept
constexpr bool operator<= (fp16 x, fp16 y) noexcept
constexpr bool operator> (fp16 x, fp16 y) noexcept
constexpr bool operator>= (fp16 x, fp16 y) noexcept
constexpr void swap (fp16 &x, fp16 &y) noexcept
ein_nodicard friend constexpr fp16 operator""_fp16 (long double v) noexcept
Detailed Description
Definition at line 27 of file fp16.hpp.
Constructor & Destructor Documentation
fp16() [1/2]
ein::fp16::fp16 () constexpr default noexcept [[always_inline]] [[artificial]]
fp16() [2/2]
ein::fp16::fp16 (float content) inline constexpr noexcept [[always_inline]] [[artificial]]
Definition at line 34 of file fp16.hpp.
: content(content) {}
Member Function Documentation
from_bits()
static constexpr fp16 ein::fp16::from_bits (uint16_t data) inline static constexpr noexcept [[always_inline]] [[artificial]] [[const]]
Definition at line 80 of file fp16.hpp.
{
    return std::bit_cast<fp16>(data);
  }
Referenced by std::numeric_limits< ein::fp16 >::denorm_min(), std::numeric_limits< ein::fp16 >::epsilon(), std::numeric_limits< ein::fp16 >::infinity(), std::numeric_limits< ein::fp16 >::lowest(), std::numeric_limits< ein::fp16 >::max(), std::numeric_limits< ein::fp16 >::min(), std::numeric_limits< ein::fp16 >::quiet_NaN(), std::numeric_limits< ein::fp16 >::round_error(), and std::numeric_limits< ein::fp16 >::signaling_NaN().
operator float()
ein::fp16::operator float () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[artificial]]
Definition at line 37 of file fp16.hpp.
{ return float(content); }
References content.
to_bits()
uint16_t ein::fp16::to_bits () const inline constexpr noexcept [[nodiscard]] [[always_inline]] [[const]]
Definition at line 85 of file fp16.hpp.
{
    return std::bit_cast<uint16_t>(content);
  }
References content.
Friends And Related Symbol Documentation
operator!=
ein_artificialein_const friend constexpr bool operator!= (fp16 x, fp16 y) friend [[nodiscard]] [[always_inline]]
Definition at line 45 of file fp16.hpp.
{
    return x.content != y.content;
  }
operator""_fp16
ein_nodicard friend constexpr fp16 operator""_fp16 (long double v) friend [[always_inline]] [[artificial]] [[const]]
Definition at line 90 of file fp16.hpp.
{
    return fp16(static_cast<float>(v));
  }
operator<
bool operator< (fp16 x, fp16 y) friend [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 55 of file fp16.hpp.
{
    return x.content < y.content;
  }
operator<=
bool operator<= (fp16 x, fp16 y) friend [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 60 of file fp16.hpp.
{
    return x.content <= y.content;
  }
operator<=>
std::partial_ordering operator<=> (fp16 x, fp16 y) friend [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 50 of file fp16.hpp.
{
    return x.content <=> y.content;
  }
operator==
bool operator== (fp16 x, fp16 y) friend [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 40 of file fp16.hpp.
{
    return x.content == y.content;
  }
operator>
bool operator> (fp16 x, fp16 y) friend [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 64 of file fp16.hpp.
{
    return x.content > y.content;
  }
operator>=
bool operator>= (fp16 x, fp16 y) friend [[nodiscard]] [[always_inline]] [[artificial]] [[const]]
Definition at line 69 of file fp16.hpp.
{
    return x.content >= y.content;
  }
swap
void swap (fp16 & x, fp16 & y) friend [[always_inline]] [[artificial]]
Definition at line 74 of file fp16.hpp.
{
    using std::swap;
    swap(x.content,y.content);
  }
Member Data Documentation
content
_Float16 ein::fp16::content
Definition at line 28 of file fp16.hpp.
Referenced by operator float(), and to_bits().
The documentation for this struct was generated from the following file:
fp16.hpp