name: 'install build tools'
description: install cmake & ninja
runs:
  using: composite
  steps:
    - name: set tool path
      run: |
        echo "/opt/cmake/bin" >> $GITHUB_PATH
        echo "/usr/local/bin" >> $GITHUB_PATH
      shell: bash
    - name: install cmake 3.30.5
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.30.5/cmake-3.30.5-linux-x86_64.sh
        sudo mkdir /opt/cmake
        sudo sh cmake-3.30.5-linux-x86_64.sh --skip-license --prefix=/opt/cmake
        sudo ln -sf /opt/cmake/bin/cmake /usr/local/bin/cmake
        which cmake && cmake --version
      shell: bash
    - name: install ninja 1.12.1
      run: |
        wget https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip
        sudo apt-get install -y unzip
        sudo unzip ninja-linux.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/ninja
        which ninja && ninja --version
      shell: bash
