var group__attributes =
[
    [ "Attribute Detection", "df/db3/group__attribute__detection.html", "df/db3/group__attribute__detection" ],
    [ "Inlining Control", "d3/d4e/group__inlining__attributes.html", "d3/d4e/group__inlining__attributes" ],
    [ "Function Multi-Versioning", "dc/da7/group__multiversioning.html", "dc/da7/group__multiversioning" ],
    [ "Calling Conventions", "d8/d64/group__calling__conventions.html", "d8/d64/group__calling__conventions" ],
    [ "Linkage Control", "d7/d68/group__linkage.html", "d7/d68/group__linkage" ],
    [ "Explicit Template Instantiation", "d2/d54/group__instantiation.html", "d2/d54/group__instantiation" ],
    [ "Typestate Analysis", "d4/dad/group__typestate__analysis.html", "d4/dad/group__typestate__analysis" ],
    [ "Thread Safety", "d5/ddc/group__thread__safety.html", "d5/ddc/group__thread__safety" ],
    [ "Handles", "dd/d8c/group__handles.html", "dd/d8c/group__handles" ],
    [ "Aliasing Control", "de/d76/group__aliasing__attributes.html", "de/d76/group__aliasing__attributes" ],
    [ "Initialization", "da/d99/group__initialization__attributes.html", "da/d99/group__initialization__attributes" ],
    [ "Purity", "db/dba/group__purity.html", "db/dba/group__purity" ],
    [ "Memory Alignment", "d4/d75/group__alignment.html", "d4/d75/group__alignment" ],
    [ "String Safety", "df/d4a/group__string__safety.html", "df/d4a/group__string__safety" ],
    [ "Object Lifetimes", "db/d36/group__lifetimes.html", "db/d36/group__lifetimes" ],
    [ "Memory Allocation", "df/dbd/group__allocation__attributes.html", "df/dbd/group__allocation__attributes" ],
    [ "Control Flow", "da/d81/group__control__flow__attributes.html", "da/d81/group__control__flow__attributes" ],
    [ "Null Safety", "d9/da3/group__null__safety__attributes.html", "d9/da3/group__null__safety__attributes" ],
    [ "CUDA", "d5/dd9/group__cuda__attributes.html", "d5/dd9/group__cuda__attributes" ],
    [ "Emitting Pragmas", "d3/d5e/group__pragmas.html", "d3/d5e/group__pragmas" ],
    [ "Loops", "da/d2b/group__loop__attributes.html", "da/d2b/group__loop__attributes" ],
    [ "attributes.hpp", "df/d6a/attributes_8hpp.html", null ]
];