var group__attributes =
[
    [ "Attribute Detection", "df/db3/group__attribute__detection.html", "df/db3/group__attribute__detection" ],
    [ "Inlining Control", "d3/d4e/group__inlining__attributes.html", "d3/d4e/group__inlining__attributes" ],
    [ "Function Multi-Versioning", "d2/db2/group__multiversioning__attributes.html", "d2/db2/group__multiversioning__attributes" ],
    [ "Calling Conventions", "d5/dc1/group__calling__convention__attributes.html", "d5/dc1/group__calling__convention__attributes" ],
    [ "Linkage Control", "dd/d43/group__linkage__attributes.html", "dd/d43/group__linkage__attributes" ],
    [ "Explicit Template Instantiation", "d9/d2b/group__instantiation__attributes.html", "d9/d2b/group__instantiation__attributes" ],
    [ "Typestate Analysis", "d4/dad/group__typestate__analysis.html", "d4/dad/group__typestate__analysis" ],
    [ "Thread Safety", "d7/d3c/group__thread__safety__attributes.html", "d7/d3c/group__thread__safety__attributes" ],
    [ "Handles", "db/dc0/group__handle__attributes.html", "db/dc0/group__handle__attributes" ],
    [ "Aliasing Control", "de/d76/group__aliasing__attributes.html", "de/d76/group__aliasing__attributes" ],
    [ "Initialization", "da/d99/group__initialization__attributes.html", "da/d99/group__initialization__attributes" ],
    [ "Purity", "d9/d3d/group__purity__attributes.html", "d9/d3d/group__purity__attributes" ],
    [ "Memory Alignment", "df/df7/group__alignment__attributes.html", "df/df7/group__alignment__attributes" ],
    [ "String Safety", "d1/d51/group__string__safety__attributes.html", "d1/d51/group__string__safety__attributes" ],
    [ "Object Lifetimes", "dd/de0/group__lifetime__attributes.html", "dd/de0/group__lifetime__attributes" ],
    [ "Memory Allocation", "df/dbd/group__allocation__attributes.html", "df/dbd/group__allocation__attributes" ],
    [ "Control Flow", "da/d81/group__control__flow__attributes.html", "da/d81/group__control__flow__attributes" ],
    [ "Null Safety", "d9/da3/group__null__safety__attributes.html", "d9/da3/group__null__safety__attributes" ],
    [ "CUDA", "d5/dd9/group__cuda__attributes.html", "d5/dd9/group__cuda__attributes" ],
    [ "Emitting Pragmas", "d3/d5e/group__pragmas.html", "d3/d5e/group__pragmas" ],
    [ "Loops", "da/d2b/group__loop__attributes.html", "da/d2b/group__loop__attributes" ],
    [ "attributes.hpp", "df/d6a/attributes_8hpp.html", null ]
];